name: Bug Report
description: Report a bug or issue with the DS Pokémon ROM Editor
title: "[Bug] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us diagnose and fix the issue.
  - type: input
    id: base-rom
    attributes:
      label: Base ROM Edited
      description: Which Pokémon ROM are you editing? (e.g., Pokémon Diamond, Pearl, Platinum, HeartGold, SoulSilver)
      placeholder: e.g., Pokémon Platinum
    validations:
      required: true
  - type: dropdown
    id: rom-language
    attributes:
      label: Language of ROM
      description: What is the language of the ROM you are editing?
      options:
        - English
        - Japanese
        - Spanish
        - French
        - German
        - Italian
        - Korean
        - Other
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running the editor on?
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true
  - type: checkboxes
    id: onedrive
    attributes:
      label: Is the ROM or editor stored in OneDrive?
      options:
        - label: Yes
        - label: No
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the bug in detail. What happened? What did you expect to happen?
      placeholder: e.g., The editor crashes when I try to open the map editor with Pokémon Platinum.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the bug.
      placeholder: |
        1. Open the editor
        2. Load Pokémon Platinum ROM
        3. Navigate to map editor
        4. Click "Open Map"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Logs
      description: If applicable, paste error logs or drag-and-drop screenshots here.
      placeholder: e.g., [Paste error log here or describe screenshot]
    validations:
      required: false
  - type: input
    id: editor-version
    attributes:
      label: Editor Version
      description: Which version of the DS Pokémon ROM Editor are you using?
      placeholder: e.g., v1.13.1
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other details, such as emulator used, specific ROM hacks applied, or environment details.
      placeholder: e.g., Using DeSmuME emulator, ROM has a custom patch applied.
    validations:
      required: false