# Force refresh - 2025-10-22
blank_issues_enabled: false
contact_links:
  - name: Kingdom of DS Hacking (DSPRE Support)
    url: https://discord.gg/te6zv2jZ
    about: Join the Kingdom of DS Hacking Discord server and use the DSPRE-specific channels for questions or support.
  - name: DS Modding Community (DSPRE Support)
    url: https://discord.gg/7b5RAX5C
    about: Join the DS Modding Community Discord server and use the DSPRE-specific channels for questions or support.