name: Test Template
description: A minimal test template
title: "[Test] "
labels: ["test"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue
    validations:
      required: true